---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/ormjwpmy/myfolder/
    - mkdir -p ${DEPLOYPATH}
    - /bin/cp index.html ${DEPLOYPATH}
    - /bin/cp styles.css ${DEPLOYPATH}
    - chmod -R 755 ${DEPLOYPATH}
